- name: When conditional directive demo
  hosts: web_server
  become: yes
  tasks:
    - name: "Installing httpd for redhat"
      yum:
        name: httpd
        state: present
      when: ansible_facts["distribution"] == "RedHat"
    - name: "Installing apache2 for ubuntu"
      apt:
        name: apache2
        state: present
      when: ansible_facts["distribution"] == "Ubuntu"

