# task1 sets env variable on remote host. Task2 sources that file, then task3, 4 we retrieve envvars.
- name: Set and get remote environment variables from tasks.
  hosts: db_server
  vars:
    environment_variables:
      - key: ENV_VAR1
        value: ENV_VAR1_VALUE
      - key: ENV_VAR2
        value: ENV_VAR2_VALUE
  tasks:
    - name: Set environment variables.
      ansible.builtin.lineinfile: 
        path: /etc/environment
        state: present
        regexp: "^{{item.key}}"
        line: "{{item.key}}={{item.value}}"
      loop:  "{{environment_variables}}"
    - name: Source /etc/environment file to reflect newly added envvars.
      shell: source /etc/environment
      args:
        executable: /bin/bash
    - name: Get & print environment variables with loop
      debug:
        msg: Environment variable => {{item}} = {{ ansible_env[item] }}
      loop: "{{ansible_env.keys() | list}}"
    - name: Get & print environment variables using with_dict
      debug:
        msg: Environment variable => {{item.key}} = {{item.value}}
      with_dict: "{{ansible_env}}"